/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type KwesForm = {
  _id: string;
  _type: "kwesForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  website_id?: number;
  name?: string;
  connected?: number;
  action?: string;
  created_at?: string;
  updated_at?: string;
  fields?: Array<{
    _key: string;
  } & FormField>;
};

export type FormspreeForm = {
  _id: string;
  _type: "formspreeForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  formspreeId?: string;
  fields?: Array<{
    _key: string;
  } & FormField>;
};

export type FormField = {
  _type: "formField";
  name?: string;
  type?: "email" | "text";
  label?: string;
};

export type HtmlForm = {
  _id: string;
  _type: "htmlForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: Slug;
  fields?: Array<{
    _key: string;
  } & FormField>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};
export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ./sanity/lib/queries.ts
// Variable: HTML_FORM_QUERY
// Query: *[_type == "htmlForm" && _id == $_id][0]
export type HTML_FORM_QUERYResult = {
  _id: string;
  _type: "htmlForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: Slug;
  fields?: Array<{
    _key: string;
  } & FormField>;
} | null;
// Variable: FORMSPREE_FORM_QUERY
// Query: *[_type == "formspreeForm" && _id == $_id][0]
export type FORMSPREE_FORM_QUERYResult = {
  _id: string;
  _type: "formspreeForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  formspreeId?: string;
  fields?: Array<{
    _key: string;
  } & FormField>;
} | null;
// Variable: KWESFORM_FORM_QUERY
// Query: *[_type == "kwesForm" && _id == $_id][0]
export type KWESFORM_FORM_QUERYResult = {
  _id: string;
  _type: "kwesForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  website_id?: number;
  name?: string;
  connected?: number;
  action?: string;
  created_at?: string;
  updated_at?: string;
  fields?: Array<{
    _key: string;
  } & FormField>;
} | null;
// Variable: ALL_KWESFORM_FORM_QUERY
// Query: *[_type == "kwesForm"]
export type ALL_KWESFORM_FORM_QUERYResult = Array<{
  _id: string;
  _type: "kwesForm";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  website_id?: number;
  name?: string;
  connected?: number;
  action?: string;
  created_at?: string;
  updated_at?: string;
  fields?: Array<{
    _key: string;
  } & FormField>;
}>;

